name       : libva-utils
version    : 2.17.1
release    : 13
source     :
    - https://github.com/intel/libva-utils/archive/refs/tags/2.17.1.tar.gz : 6ea5993c3eba230a979fa9d35b4cad8df06d4474a773dc0918033bf50353f966
license    : MIT
component  : system.utils
summary    : Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
description: |
    Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
