name       : libva-utils
version    : 2.18.1
release    : 15
source     :
    - https://github.com/intel/libva-utils/archive/refs/tags/2.18.1.tar.gz : 724a54524d9156967d3508f294ce5c45d94cb8f7326537c24ee7fcf59e70de91
license    : MIT
component  : system.utils
summary    : Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
description: |
    Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
