name       : libva-utils
version    : 2.1.0
release    : 2
source     :
    - https://github.com/intel/libva-utils/releases/download/2.1.0/libva-utils-2.1.0.tar.bz2 : f6a7790c3dcc56537372c90a83036a3136194a8b397e84e97bf9cc9254fa2c51
license    : MIT
component  : system.utils
summary    : Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
description: |
    Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
