name       : libva-utils
version    : 2.16.0
release    : 12
source     :
    - https://github.com/intel/libva-utils/archive/refs/tags/2.16.0.tar.gz : 646c9bfff6a83504c48de2c786c9514ca30c5e916127faf00f143ef8147ee950
license    : MIT
component  : system.utils
summary    : Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
description: |
    Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
