name       : libva-utils
version    : 2.10.0
release    : 7
source     :
    - https://github.com/intel/libva-utils/releases/download/2.10.0/libva-utils-2.10.0.tar.bz2 : 33f06929faa395f55ec816432679219c56d70850bf465c848f0418e8a4f0352b
license    : MIT
component  : system.utils
summary    : Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
description: |
    Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
