name       : libva-utils
version    : 2.5.0
release    : 5
source     :
    - https://github.com/intel/libva-utils/releases/download/2.5.0/libva-utils-2.5.0.tar.bz2 : 9238c9d5110d60f935683390b8383fdac3507346384cd5f117a23c6db1d72a17
license    : MIT
component  : system.utils
summary    : Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
description: |
    Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
