name       : libva-utils
version    : 2.0.0
release    : 1
source     :
    - https://github.com/01org/libva-utils/releases/download/2.0.0/libva-utils-2.0.0.tar.bz2 : a921df31311d8f49d2e392a5fc2a068d79f89aeb588309fbff24365310dbc5f6
license    : MIT
component  : system.utils
summary    : Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
description: |
    Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
