name       : libva-utils
version    : 2.2.0
release    : 3
source     :
    - https://github.com/intel/libva-utils/releases/download/2.2.0/libva-utils-2.2.0.tar.bz2 : ed7a6ed1fab657df4e83ea11f90310efcf31c27828f32d65351a28ca3c404dc0
license    : MIT
component  : system.utils
summary    : Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
description: |
    Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
