name       : libva-utils
version    : 2.13.0
release    : 8
source     :
    - https://github.com/intel/libva-utils/releases/download/2.13.0/libva-utils-2.13.0.tar.bz2 : db3ae0bd63c2a3f6ef498450c29ffc99c387ce611e1eb5db6a8da1f88845d612
license    : MIT
component  : system.utils
summary    : Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
description: |
    Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
