name       : libva-utils
version    : 2.3.0
release    : 4
source     :
    - https://github.com/intel/libva-utils/archive/2.3.0.tar.gz : f338497b867bbc9bf008e4892eaebda08955785dc7eb2005855bba5f1a20b037
license    : MIT
component  : system.utils
summary    : Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
description: |
    Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
