name       : libva-utils
version    : 2.18.1
release    : 14
source     :
    - https://github.com/intel/libva-utils/archive/refs/tags/2.18.1.tar.gz : 79da4a683dc4b10639edd7ad4c9434789ef208f5361f87aca9bc986a4ebcb155
license    : MIT
component  : system.utils
summary    : Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
description: |
    Libva-utils is a collection of tests for VA-API (VIdeo Acceleration API).
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libva)
    - pkgconfig(wayland-client)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
